// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: SendGridServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockSendGridServiceInterface is a mock of SendGridServiceInterface interface.
type MockSendGridServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSendGridServiceInterfaceMockRecorder
}

// MockSendGridServiceInterfaceMockRecorder is the mock recorder for MockSendGridServiceInterface.
type MockSendGridServiceInterfaceMockRecorder struct {
	mock *MockSendGridServiceInterface
}

// NewMockSendGridServiceInterface creates a new mock instance.
func NewMockSendGridServiceInterface(ctrl *gomock.Controller) *MockSendGridServiceInterface {
	mock := &MockSendGridServiceInterface{ctrl: ctrl}
	mock.recorder = &MockSendGridServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSendGridServiceInterface) EXPECT() *MockSendGridServiceInterfaceMockRecorder {
	return m.recorder
}

// GetWebhookSettings mocks base method.
func (m *MockSendGridServiceInterface) GetWebhookSettings(arg0 context.Context, arg1 domain.SendGridSettings) (*domain.SendGridWebhookSettings, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWebhookSettings", arg0, arg1)
	ret0, _ := ret[0].(*domain.SendGridWebhookSettings)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWebhookSettings indicates an expected call of GetWebhookSettings.
func (mr *MockSendGridServiceInterfaceMockRecorder) GetWebhookSettings(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWebhookSettings", reflect.TypeOf((*MockSendGridServiceInterface)(nil).GetWebhookSettings), arg0, arg1)
}

// UpdateWebhookSettings mocks base method.
func (m *MockSendGridServiceInterface) UpdateWebhookSettings(arg0 context.Context, arg1 domain.SendGridSettings, arg2 domain.SendGridWebhookSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebhookSettings", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebhookSettings indicates an expected call of UpdateWebhookSettings.
func (mr *MockSendGridServiceInterfaceMockRecorder) UpdateWebhookSettings(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebhookSettings", reflect.TypeOf((*MockSendGridServiceInterface)(nil).UpdateWebhookSettings), arg0, arg1, arg2)
}
