// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BlogPostRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBlogPostRepository is a mock of BlogPostRepository interface.
type MockBlogPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlogPostRepositoryMockRecorder
}

// MockBlogPostRepositoryMockRecorder is the mock recorder for MockBlogPostRepository.
type MockBlogPostRepositoryMockRecorder struct {
	mock *MockBlogPostRepository
}

// NewMockBlogPostRepository creates a new mock instance.
func NewMockBlogPostRepository(ctrl *gomock.Controller) *MockBlogPostRepository {
	mock := &MockBlogPostRepository{ctrl: ctrl}
	mock.recorder = &MockBlogPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogPostRepository) EXPECT() *MockBlogPostRepositoryMockRecorder {
	return m.recorder
}

// CreatePost mocks base method.
func (m *MockBlogPostRepository) CreatePost(arg0 context.Context, arg1 *domain.BlogPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockBlogPostRepositoryMockRecorder) CreatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockBlogPostRepository)(nil).CreatePost), arg0, arg1)
}

// CreatePostTx mocks base method.
func (m *MockBlogPostRepository) CreatePostTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePostTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePostTx indicates an expected call of CreatePostTx.
func (mr *MockBlogPostRepositoryMockRecorder) CreatePostTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).CreatePostTx), arg0, arg1, arg2)
}

// DeletePost mocks base method.
func (m *MockBlogPostRepository) DeletePost(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockBlogPostRepositoryMockRecorder) DeletePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockBlogPostRepository)(nil).DeletePost), arg0, arg1)
}

// DeletePostTx mocks base method.
func (m *MockBlogPostRepository) DeletePostTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePostTx indicates an expected call of DeletePostTx.
func (mr *MockBlogPostRepositoryMockRecorder) DeletePostTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).DeletePostTx), arg0, arg1, arg2)
}

// DeletePostsByCategoryIDTx mocks base method.
func (m *MockBlogPostRepository) DeletePostsByCategoryIDTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePostsByCategoryIDTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePostsByCategoryIDTx indicates an expected call of DeletePostsByCategoryIDTx.
func (mr *MockBlogPostRepositoryMockRecorder) DeletePostsByCategoryIDTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePostsByCategoryIDTx", reflect.TypeOf((*MockBlogPostRepository)(nil).DeletePostsByCategoryIDTx), arg0, arg1, arg2)
}

// GetPost mocks base method.
func (m *MockBlogPostRepository) GetPost(arg0 context.Context, arg1 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockBlogPostRepositoryMockRecorder) GetPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockBlogPostRepository)(nil).GetPost), arg0, arg1)
}

// GetPostByCategoryAndSlug mocks base method.
func (m *MockBlogPostRepository) GetPostByCategoryAndSlug(arg0 context.Context, arg1, arg2 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByCategoryAndSlug", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByCategoryAndSlug indicates an expected call of GetPostByCategoryAndSlug.
func (mr *MockBlogPostRepositoryMockRecorder) GetPostByCategoryAndSlug(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByCategoryAndSlug", reflect.TypeOf((*MockBlogPostRepository)(nil).GetPostByCategoryAndSlug), arg0, arg1, arg2)
}

// GetPostBySlug mocks base method.
func (m *MockBlogPostRepository) GetPostBySlug(arg0 context.Context, arg1 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostBySlug", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostBySlug indicates an expected call of GetPostBySlug.
func (mr *MockBlogPostRepositoryMockRecorder) GetPostBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostBySlug", reflect.TypeOf((*MockBlogPostRepository)(nil).GetPostBySlug), arg0, arg1)
}

// GetPostBySlugTx mocks base method.
func (m *MockBlogPostRepository) GetPostBySlugTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostBySlugTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostBySlugTx indicates an expected call of GetPostBySlugTx.
func (mr *MockBlogPostRepositoryMockRecorder) GetPostBySlugTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostBySlugTx", reflect.TypeOf((*MockBlogPostRepository)(nil).GetPostBySlugTx), arg0, arg1, arg2)
}

// GetPostTx mocks base method.
func (m *MockBlogPostRepository) GetPostTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostTx indicates an expected call of GetPostTx.
func (mr *MockBlogPostRepositoryMockRecorder) GetPostTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).GetPostTx), arg0, arg1, arg2)
}

// ListPosts mocks base method.
func (m *MockBlogPostRepository) ListPosts(arg0 context.Context, arg1 domain.ListBlogPostsRequest) (*domain.BlogPostListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPostListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockBlogPostRepositoryMockRecorder) ListPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockBlogPostRepository)(nil).ListPosts), arg0, arg1)
}

// PublishPost mocks base method.
func (m *MockBlogPostRepository) PublishPost(arg0 context.Context, arg1 string, arg2 *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPost", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPost indicates an expected call of PublishPost.
func (mr *MockBlogPostRepositoryMockRecorder) PublishPost(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPost", reflect.TypeOf((*MockBlogPostRepository)(nil).PublishPost), arg0, arg1, arg2)
}

// PublishPostTx mocks base method.
func (m *MockBlogPostRepository) PublishPostTx(arg0 context.Context, arg1 *sql.Tx, arg2 string, arg3 *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPostTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPostTx indicates an expected call of PublishPostTx.
func (mr *MockBlogPostRepositoryMockRecorder) PublishPostTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).PublishPostTx), arg0, arg1, arg2, arg3)
}

// UnpublishPost mocks base method.
func (m *MockBlogPostRepository) UnpublishPost(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishPost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishPost indicates an expected call of UnpublishPost.
func (mr *MockBlogPostRepositoryMockRecorder) UnpublishPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishPost", reflect.TypeOf((*MockBlogPostRepository)(nil).UnpublishPost), arg0, arg1)
}

// UnpublishPostTx mocks base method.
func (m *MockBlogPostRepository) UnpublishPostTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishPostTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishPostTx indicates an expected call of UnpublishPostTx.
func (mr *MockBlogPostRepositoryMockRecorder) UnpublishPostTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishPostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).UnpublishPostTx), arg0, arg1, arg2)
}

// UpdatePost mocks base method.
func (m *MockBlogPostRepository) UpdatePost(arg0 context.Context, arg1 *domain.BlogPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockBlogPostRepositoryMockRecorder) UpdatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockBlogPostRepository)(nil).UpdatePost), arg0, arg1)
}

// UpdatePostTx mocks base method.
func (m *MockBlogPostRepository) UpdatePostTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogPost) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePostTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePostTx indicates an expected call of UpdatePostTx.
func (mr *MockBlogPostRepositoryMockRecorder) UpdatePostTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePostTx", reflect.TypeOf((*MockBlogPostRepository)(nil).UpdatePostTx), arg0, arg1, arg2)
}

// WithTransaction mocks base method.
func (m *MockBlogPostRepository) WithTransaction(arg0 context.Context, arg1 string, arg2 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockBlogPostRepositoryMockRecorder) WithTransaction(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockBlogPostRepository)(nil).WithTransaction), arg0, arg1, arg2)
}
