// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: TaskService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTaskService is a mock of TaskService interface.
type MockTaskService struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceMockRecorder
}

// MockTaskServiceMockRecorder is the mock recorder for MockTaskService.
type MockTaskServiceMockRecorder struct {
	mock *MockTaskService
}

// NewMockTaskService creates a new mock instance.
func NewMockTaskService(ctrl *gomock.Controller) *MockTaskService {
	mock := &MockTaskService{ctrl: ctrl}
	mock.recorder = &MockTaskServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskService) EXPECT() *MockTaskServiceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskService) CreateTask(arg0 context.Context, arg1 string, arg2 *domain.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceMockRecorder) CreateTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskService)(nil).CreateTask), arg0, arg1, arg2)
}

// DeleteTask mocks base method.
func (m *MockTaskService) DeleteTask(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceMockRecorder) DeleteTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskService)(nil).DeleteTask), arg0, arg1, arg2)
}

// ExecutePendingTasks mocks base method.
func (m *MockTaskService) ExecutePendingTasks(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutePendingTasks", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecutePendingTasks indicates an expected call of ExecutePendingTasks.
func (mr *MockTaskServiceMockRecorder) ExecutePendingTasks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutePendingTasks", reflect.TypeOf((*MockTaskService)(nil).ExecutePendingTasks), arg0, arg1)
}

// ExecuteTask mocks base method.
func (m *MockTaskService) ExecuteTask(arg0 context.Context, arg1, arg2 string, arg3 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTask", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTask indicates an expected call of ExecuteTask.
func (mr *MockTaskServiceMockRecorder) ExecuteTask(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTask", reflect.TypeOf((*MockTaskService)(nil).ExecuteTask), arg0, arg1, arg2, arg3)
}

// GetLastCronRun mocks base method.
func (m *MockTaskService) GetLastCronRun(arg0 context.Context) (*time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCronRun", arg0)
	ret0, _ := ret[0].(*time.Time)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastCronRun indicates an expected call of GetLastCronRun.
func (mr *MockTaskServiceMockRecorder) GetLastCronRun(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCronRun", reflect.TypeOf((*MockTaskService)(nil).GetLastCronRun), arg0)
}

// GetProcessor mocks base method.
func (m *MockTaskService) GetProcessor(arg0 string) (domain.TaskProcessor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcessor", arg0)
	ret0, _ := ret[0].(domain.TaskProcessor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProcessor indicates an expected call of GetProcessor.
func (mr *MockTaskServiceMockRecorder) GetProcessor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcessor", reflect.TypeOf((*MockTaskService)(nil).GetProcessor), arg0)
}

// GetTask mocks base method.
func (m *MockTaskService) GetTask(arg0 context.Context, arg1, arg2 string) (*domain.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskServiceMockRecorder) GetTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskService)(nil).GetTask), arg0, arg1, arg2)
}

// IsAutoExecuteEnabled mocks base method.
func (m *MockTaskService) IsAutoExecuteEnabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAutoExecuteEnabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAutoExecuteEnabled indicates an expected call of IsAutoExecuteEnabled.
func (mr *MockTaskServiceMockRecorder) IsAutoExecuteEnabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAutoExecuteEnabled", reflect.TypeOf((*MockTaskService)(nil).IsAutoExecuteEnabled))
}

// ListTasks mocks base method.
func (m *MockTaskService) ListTasks(arg0 context.Context, arg1 string, arg2 domain.TaskFilter) (*domain.TaskListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTasks", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.TaskListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTasks indicates an expected call of ListTasks.
func (mr *MockTaskServiceMockRecorder) ListTasks(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTasks", reflect.TypeOf((*MockTaskService)(nil).ListTasks), arg0, arg1, arg2)
}

// RegisterProcessor mocks base method.
func (m *MockTaskService) RegisterProcessor(arg0 domain.TaskProcessor) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterProcessor", arg0)
}

// RegisterProcessor indicates an expected call of RegisterProcessor.
func (mr *MockTaskServiceMockRecorder) RegisterProcessor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterProcessor", reflect.TypeOf((*MockTaskService)(nil).RegisterProcessor), arg0)
}

// ResetTask mocks base method.
func (m *MockTaskService) ResetTask(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetTask indicates an expected call of ResetTask.
func (mr *MockTaskServiceMockRecorder) ResetTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetTask", reflect.TypeOf((*MockTaskService)(nil).ResetTask), arg0, arg1, arg2)
}

// SubscribeToBroadcastEvents mocks base method.
func (m *MockTaskService) SubscribeToBroadcastEvents(arg0 domain.EventBus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SubscribeToBroadcastEvents", arg0)
}

// SubscribeToBroadcastEvents indicates an expected call of SubscribeToBroadcastEvents.
func (mr *MockTaskServiceMockRecorder) SubscribeToBroadcastEvents(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeToBroadcastEvents", reflect.TypeOf((*MockTaskService)(nil).SubscribeToBroadcastEvents), arg0)
}

// TriggerTask mocks base method.
func (m *MockTaskService) TriggerTask(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TriggerTask", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// TriggerTask indicates an expected call of TriggerTask.
func (mr *MockTaskServiceMockRecorder) TriggerTask(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerTask", reflect.TypeOf((*MockTaskService)(nil).TriggerTask), arg0, arg1, arg2)
}
