// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: ContactService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockContactService is a mock of ContactService interface.
type MockContactService struct {
	ctrl     *gomock.Controller
	recorder *MockContactServiceMockRecorder
}

// MockContactServiceMockRecorder is the mock recorder for MockContactService.
type MockContactServiceMockRecorder struct {
	mock *MockContactService
}

// NewMockContactService creates a new mock instance.
func NewMockContactService(ctrl *gomock.Controller) *MockContactService {
	mock := &MockContactService{ctrl: ctrl}
	mock.recorder = &MockContactServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactService) EXPECT() *MockContactServiceMockRecorder {
	return m.recorder
}

// BatchImportContacts mocks base method.
func (m *MockContactService) BatchImportContacts(arg0 context.Context, arg1 string, arg2 []*domain.Contact, arg3 []string) *domain.BatchImportContactsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchImportContacts", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.BatchImportContactsResponse)
	return ret0
}

// BatchImportContacts indicates an expected call of BatchImportContacts.
func (mr *MockContactServiceMockRecorder) BatchImportContacts(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchImportContacts", reflect.TypeOf((*MockContactService)(nil).BatchImportContacts), arg0, arg1, arg2, arg3)
}

// CountContacts mocks base method.
func (m *MockContactService) CountContacts(arg0 context.Context, arg1 string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountContacts", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountContacts indicates an expected call of CountContacts.
func (mr *MockContactServiceMockRecorder) CountContacts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountContacts", reflect.TypeOf((*MockContactService)(nil).CountContacts), arg0, arg1)
}

// DeleteContact mocks base method.
func (m *MockContactService) DeleteContact(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContact indicates an expected call of DeleteContact.
func (mr *MockContactServiceMockRecorder) DeleteContact(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContact", reflect.TypeOf((*MockContactService)(nil).DeleteContact), arg0, arg1, arg2)
}

// GetContactByEmail mocks base method.
func (m *MockContactService) GetContactByEmail(arg0 context.Context, arg1, arg2 string) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByEmail indicates an expected call of GetContactByEmail.
func (mr *MockContactServiceMockRecorder) GetContactByEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByEmail", reflect.TypeOf((*MockContactService)(nil).GetContactByEmail), arg0, arg1, arg2)
}

// GetContactByExternalID mocks base method.
func (m *MockContactService) GetContactByExternalID(arg0 context.Context, arg1, arg2 string) (*domain.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactByExternalID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactByExternalID indicates an expected call of GetContactByExternalID.
func (mr *MockContactServiceMockRecorder) GetContactByExternalID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactByExternalID", reflect.TypeOf((*MockContactService)(nil).GetContactByExternalID), arg0, arg1, arg2)
}

// GetContacts mocks base method.
func (m *MockContactService) GetContacts(arg0 context.Context, arg1 *domain.GetContactsRequest) (*domain.GetContactsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContacts", arg0, arg1)
	ret0, _ := ret[0].(*domain.GetContactsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContacts indicates an expected call of GetContacts.
func (mr *MockContactServiceMockRecorder) GetContacts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContacts", reflect.TypeOf((*MockContactService)(nil).GetContacts), arg0, arg1)
}

// UpsertContact mocks base method.
func (m *MockContactService) UpsertContact(arg0 context.Context, arg1 string, arg2 *domain.Contact) domain.UpsertContactOperation {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertContact", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.UpsertContactOperation)
	return ret0
}

// UpsertContact indicates an expected call of UpsertContact.
func (mr *MockContactServiceMockRecorder) UpsertContact(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertContact", reflect.TypeOf((*MockContactService)(nil).UpsertContact), arg0, arg1, arg2)
}
