// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: ContactTimelineService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockContactTimelineService is a mock of ContactTimelineService interface.
type MockContactTimelineService struct {
	ctrl     *gomock.Controller
	recorder *MockContactTimelineServiceMockRecorder
}

// MockContactTimelineServiceMockRecorder is the mock recorder for MockContactTimelineService.
type MockContactTimelineServiceMockRecorder struct {
	mock *MockContactTimelineService
}

// NewMockContactTimelineService creates a new mock instance.
func NewMockContactTimelineService(ctrl *gomock.Controller) *MockContactTimelineService {
	mock := &MockContactTimelineService{ctrl: ctrl}
	mock.recorder = &MockContactTimelineServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactTimelineService) EXPECT() *MockContactTimelineServiceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockContactTimelineService) List(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 *string) ([]*domain.ContactTimelineEntry, *string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.ContactTimelineEntry)
	ret1, _ := ret[1].(*string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockContactTimelineServiceMockRecorder) List(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockContactTimelineService)(nil).List), arg0, arg1, arg2, arg3, arg4)
}
