// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BlogThemeRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBlogThemeRepository is a mock of BlogThemeRepository interface.
type MockBlogThemeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlogThemeRepositoryMockRecorder
}

// MockBlogThemeRepositoryMockRecorder is the mock recorder for MockBlogThemeRepository.
type MockBlogThemeRepositoryMockRecorder struct {
	mock *MockBlogThemeRepository
}

// NewMockBlogThemeRepository creates a new mock instance.
func NewMockBlogThemeRepository(ctrl *gomock.Controller) *MockBlogThemeRepository {
	mock := &MockBlogThemeRepository{ctrl: ctrl}
	mock.recorder = &MockBlogThemeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogThemeRepository) EXPECT() *MockBlogThemeRepositoryMockRecorder {
	return m.recorder
}

// CreateTheme mocks base method.
func (m *MockBlogThemeRepository) CreateTheme(arg0 context.Context, arg1 *domain.BlogTheme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTheme", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTheme indicates an expected call of CreateTheme.
func (mr *MockBlogThemeRepositoryMockRecorder) CreateTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTheme", reflect.TypeOf((*MockBlogThemeRepository)(nil).CreateTheme), arg0, arg1)
}

// CreateThemeTx mocks base method.
func (m *MockBlogThemeRepository) CreateThemeTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogTheme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateThemeTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateThemeTx indicates an expected call of CreateThemeTx.
func (mr *MockBlogThemeRepositoryMockRecorder) CreateThemeTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateThemeTx", reflect.TypeOf((*MockBlogThemeRepository)(nil).CreateThemeTx), arg0, arg1, arg2)
}

// GetPublishedTheme mocks base method.
func (m *MockBlogThemeRepository) GetPublishedTheme(arg0 context.Context) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedTheme", arg0)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedTheme indicates an expected call of GetPublishedTheme.
func (mr *MockBlogThemeRepositoryMockRecorder) GetPublishedTheme(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedTheme", reflect.TypeOf((*MockBlogThemeRepository)(nil).GetPublishedTheme), arg0)
}

// GetPublishedThemeTx mocks base method.
func (m *MockBlogThemeRepository) GetPublishedThemeTx(arg0 context.Context, arg1 *sql.Tx) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedThemeTx", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedThemeTx indicates an expected call of GetPublishedThemeTx.
func (mr *MockBlogThemeRepositoryMockRecorder) GetPublishedThemeTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedThemeTx", reflect.TypeOf((*MockBlogThemeRepository)(nil).GetPublishedThemeTx), arg0, arg1)
}

// GetTheme mocks base method.
func (m *MockBlogThemeRepository) GetTheme(arg0 context.Context, arg1 int) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockBlogThemeRepositoryMockRecorder) GetTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockBlogThemeRepository)(nil).GetTheme), arg0, arg1)
}

// GetThemeTx mocks base method.
func (m *MockBlogThemeRepository) GetThemeTx(arg0 context.Context, arg1 *sql.Tx, arg2 int) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThemeTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThemeTx indicates an expected call of GetThemeTx.
func (mr *MockBlogThemeRepositoryMockRecorder) GetThemeTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThemeTx", reflect.TypeOf((*MockBlogThemeRepository)(nil).GetThemeTx), arg0, arg1, arg2)
}

// ListThemes mocks base method.
func (m *MockBlogThemeRepository) ListThemes(arg0 context.Context, arg1 domain.ListBlogThemesRequest) (*domain.BlogThemeListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThemes", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogThemeListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThemes indicates an expected call of ListThemes.
func (mr *MockBlogThemeRepositoryMockRecorder) ListThemes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThemes", reflect.TypeOf((*MockBlogThemeRepository)(nil).ListThemes), arg0, arg1)
}

// PublishTheme mocks base method.
func (m *MockBlogThemeRepository) PublishTheme(arg0 context.Context, arg1 int, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTheme", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTheme indicates an expected call of PublishTheme.
func (mr *MockBlogThemeRepositoryMockRecorder) PublishTheme(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTheme", reflect.TypeOf((*MockBlogThemeRepository)(nil).PublishTheme), arg0, arg1, arg2)
}

// PublishThemeTx mocks base method.
func (m *MockBlogThemeRepository) PublishThemeTx(arg0 context.Context, arg1 *sql.Tx, arg2 int, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishThemeTx", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishThemeTx indicates an expected call of PublishThemeTx.
func (mr *MockBlogThemeRepositoryMockRecorder) PublishThemeTx(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishThemeTx", reflect.TypeOf((*MockBlogThemeRepository)(nil).PublishThemeTx), arg0, arg1, arg2, arg3)
}

// UpdateTheme mocks base method.
func (m *MockBlogThemeRepository) UpdateTheme(arg0 context.Context, arg1 *domain.BlogTheme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTheme", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTheme indicates an expected call of UpdateTheme.
func (mr *MockBlogThemeRepositoryMockRecorder) UpdateTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTheme", reflect.TypeOf((*MockBlogThemeRepository)(nil).UpdateTheme), arg0, arg1)
}

// UpdateThemeTx mocks base method.
func (m *MockBlogThemeRepository) UpdateThemeTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogTheme) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateThemeTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateThemeTx indicates an expected call of UpdateThemeTx.
func (mr *MockBlogThemeRepositoryMockRecorder) UpdateThemeTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateThemeTx", reflect.TypeOf((*MockBlogThemeRepository)(nil).UpdateThemeTx), arg0, arg1, arg2)
}

// WithTransaction mocks base method.
func (m *MockBlogThemeRepository) WithTransaction(arg0 context.Context, arg1 string, arg2 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockBlogThemeRepositoryMockRecorder) WithTransaction(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockBlogThemeRepository)(nil).WithTransaction), arg0, arg1, arg2)
}
