// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: ContactListService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockContactListService is a mock of ContactListService interface.
type MockContactListService struct {
	ctrl     *gomock.Controller
	recorder *MockContactListServiceMockRecorder
}

// MockContactListServiceMockRecorder is the mock recorder for MockContactListService.
type MockContactListServiceMockRecorder struct {
	mock *MockContactListService
}

// NewMockContactListService creates a new mock instance.
func NewMockContactListService(ctrl *gomock.Controller) *MockContactListService {
	mock := &MockContactListService{ctrl: ctrl}
	mock.recorder = &MockContactListServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContactListService) EXPECT() *MockContactListServiceMockRecorder {
	return m.recorder
}

// GetContactListByIDs mocks base method.
func (m *MockContactListService) GetContactListByIDs(arg0 context.Context, arg1, arg2, arg3 string) (*domain.ContactList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactListByIDs", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*domain.ContactList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactListByIDs indicates an expected call of GetContactListByIDs.
func (mr *MockContactListServiceMockRecorder) GetContactListByIDs(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactListByIDs", reflect.TypeOf((*MockContactListService)(nil).GetContactListByIDs), arg0, arg1, arg2, arg3)
}

// GetContactsByListID mocks base method.
func (m *MockContactListService) GetContactsByListID(arg0 context.Context, arg1, arg2 string) ([]*domain.ContactList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContactsByListID", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.ContactList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContactsByListID indicates an expected call of GetContactsByListID.
func (mr *MockContactListServiceMockRecorder) GetContactsByListID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContactsByListID", reflect.TypeOf((*MockContactListService)(nil).GetContactsByListID), arg0, arg1, arg2)
}

// GetListsByEmail mocks base method.
func (m *MockContactListService) GetListsByEmail(arg0 context.Context, arg1, arg2 string) ([]*domain.ContactList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListsByEmail", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.ContactList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListsByEmail indicates an expected call of GetListsByEmail.
func (mr *MockContactListServiceMockRecorder) GetListsByEmail(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListsByEmail", reflect.TypeOf((*MockContactListService)(nil).GetListsByEmail), arg0, arg1, arg2)
}

// RemoveContactFromList mocks base method.
func (m *MockContactListService) RemoveContactFromList(arg0 context.Context, arg1, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContactFromList", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContactFromList indicates an expected call of RemoveContactFromList.
func (mr *MockContactListServiceMockRecorder) RemoveContactFromList(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContactFromList", reflect.TypeOf((*MockContactListService)(nil).RemoveContactFromList), arg0, arg1, arg2, arg3)
}

// UpdateContactListStatus mocks base method.
func (m *MockContactListService) UpdateContactListStatus(arg0 context.Context, arg1, arg2, arg3 string, arg4 domain.ContactListStatus) (*domain.UpdateContactListStatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactListStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(*domain.UpdateContactListStatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContactListStatus indicates an expected call of UpdateContactListStatus.
func (mr *MockContactListServiceMockRecorder) UpdateContactListStatus(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactListStatus", reflect.TypeOf((*MockContactListService)(nil).UpdateContactListStatus), arg0, arg1, arg2, arg3, arg4)
}
