// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebhookDeliveryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookDeliveryRepository is a mock of WebhookDeliveryRepository interface.
type MockWebhookDeliveryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookDeliveryRepositoryMockRecorder
}

// MockWebhookDeliveryRepositoryMockRecorder is the mock recorder for MockWebhookDeliveryRepository.
type MockWebhookDeliveryRepositoryMockRecorder struct {
	mock *MockWebhookDeliveryRepository
}

// NewMockWebhookDeliveryRepository creates a new mock instance.
func NewMockWebhookDeliveryRepository(ctrl *gomock.Controller) *MockWebhookDeliveryRepository {
	mock := &MockWebhookDeliveryRepository{ctrl: ctrl}
	mock.recorder = &MockWebhookDeliveryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookDeliveryRepository) EXPECT() *MockWebhookDeliveryRepositoryMockRecorder {
	return m.recorder
}

// CleanupOldDeliveries mocks base method.
func (m *MockWebhookDeliveryRepository) CleanupOldDeliveries(arg0 context.Context, arg1 string, arg2 int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupOldDeliveries", arg0, arg1, arg2)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupOldDeliveries indicates an expected call of CleanupOldDeliveries.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) CleanupOldDeliveries(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupOldDeliveries", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).CleanupOldDeliveries), arg0, arg1, arg2)
}

// Create mocks base method.
func (m *MockWebhookDeliveryRepository) Create(arg0 context.Context, arg1 string, arg2 *domain.WebhookDelivery) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) Create(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).Create), arg0, arg1, arg2)
}

// GetPendingForWorkspace mocks base method.
func (m *MockWebhookDeliveryRepository) GetPendingForWorkspace(arg0 context.Context, arg1 string, arg2 int) ([]*domain.WebhookDelivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingForWorkspace", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*domain.WebhookDelivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingForWorkspace indicates an expected call of GetPendingForWorkspace.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) GetPendingForWorkspace(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingForWorkspace", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).GetPendingForWorkspace), arg0, arg1, arg2)
}

// ListAll mocks base method.
func (m *MockWebhookDeliveryRepository) ListAll(arg0 context.Context, arg1 string, arg2 *string, arg3, arg4 int) ([]*domain.WebhookDelivery, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].([]*domain.WebhookDelivery)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListAll indicates an expected call of ListAll.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) ListAll(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).ListAll), arg0, arg1, arg2, arg3, arg4)
}

// MarkDelivered mocks base method.
func (m *MockWebhookDeliveryRepository) MarkDelivered(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkDelivered", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkDelivered indicates an expected call of MarkDelivered.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) MarkDelivered(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkDelivered", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).MarkDelivered), arg0, arg1, arg2, arg3, arg4)
}

// MarkFailed mocks base method.
func (m *MockWebhookDeliveryRepository) MarkFailed(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 string, arg5 *int, arg6 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkFailed", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) MarkFailed(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkFailed", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).MarkFailed), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// ScheduleRetry mocks base method.
func (m *MockWebhookDeliveryRepository) ScheduleRetry(arg0 context.Context, arg1, arg2 string, arg3 time.Time, arg4 int, arg5 *int, arg6, arg7 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ScheduleRetry", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	ret0, _ := ret[0].(error)
	return ret0
}

// ScheduleRetry indicates an expected call of ScheduleRetry.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) ScheduleRetry(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ScheduleRetry", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).ScheduleRetry), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
}

// UpdateStatus mocks base method.
func (m *MockWebhookDeliveryRepository) UpdateStatus(arg0 context.Context, arg1, arg2, arg3 string, arg4 int, arg5 *int, arg6, arg7 *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockWebhookDeliveryRepositoryMockRecorder) UpdateStatus(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockWebhookDeliveryRepository)(nil).UpdateStatus), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)
}
