// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BlogCategoryRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBlogCategoryRepository is a mock of BlogCategoryRepository interface.
type MockBlogCategoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlogCategoryRepositoryMockRecorder
}

// MockBlogCategoryRepositoryMockRecorder is the mock recorder for MockBlogCategoryRepository.
type MockBlogCategoryRepositoryMockRecorder struct {
	mock *MockBlogCategoryRepository
}

// NewMockBlogCategoryRepository creates a new mock instance.
func NewMockBlogCategoryRepository(ctrl *gomock.Controller) *MockBlogCategoryRepository {
	mock := &MockBlogCategoryRepository{ctrl: ctrl}
	mock.recorder = &MockBlogCategoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogCategoryRepository) EXPECT() *MockBlogCategoryRepositoryMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockBlogCategoryRepository) CreateCategory(arg0 context.Context, arg1 *domain.BlogCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockBlogCategoryRepositoryMockRecorder) CreateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockBlogCategoryRepository)(nil).CreateCategory), arg0, arg1)
}

// CreateCategoryTx mocks base method.
func (m *MockBlogCategoryRepository) CreateCategoryTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategoryTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategoryTx indicates an expected call of CreateCategoryTx.
func (mr *MockBlogCategoryRepositoryMockRecorder) CreateCategoryTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategoryTx", reflect.TypeOf((*MockBlogCategoryRepository)(nil).CreateCategoryTx), arg0, arg1, arg2)
}

// DeleteCategory mocks base method.
func (m *MockBlogCategoryRepository) DeleteCategory(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockBlogCategoryRepositoryMockRecorder) DeleteCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockBlogCategoryRepository)(nil).DeleteCategory), arg0, arg1)
}

// DeleteCategoryTx mocks base method.
func (m *MockBlogCategoryRepository) DeleteCategoryTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategoryTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategoryTx indicates an expected call of DeleteCategoryTx.
func (mr *MockBlogCategoryRepositoryMockRecorder) DeleteCategoryTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategoryTx", reflect.TypeOf((*MockBlogCategoryRepository)(nil).DeleteCategoryTx), arg0, arg1, arg2)
}

// GetCategoriesByIDs mocks base method.
func (m *MockBlogCategoryRepository) GetCategoriesByIDs(arg0 context.Context, arg1 []string) ([]*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoriesByIDs", arg0, arg1)
	ret0, _ := ret[0].([]*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoriesByIDs indicates an expected call of GetCategoriesByIDs.
func (mr *MockBlogCategoryRepositoryMockRecorder) GetCategoriesByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoriesByIDs", reflect.TypeOf((*MockBlogCategoryRepository)(nil).GetCategoriesByIDs), arg0, arg1)
}

// GetCategory mocks base method.
func (m *MockBlogCategoryRepository) GetCategory(arg0 context.Context, arg1 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockBlogCategoryRepositoryMockRecorder) GetCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockBlogCategoryRepository)(nil).GetCategory), arg0, arg1)
}

// GetCategoryBySlug mocks base method.
func (m *MockBlogCategoryRepository) GetCategoryBySlug(arg0 context.Context, arg1 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBySlug", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBySlug indicates an expected call of GetCategoryBySlug.
func (mr *MockBlogCategoryRepositoryMockRecorder) GetCategoryBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBySlug", reflect.TypeOf((*MockBlogCategoryRepository)(nil).GetCategoryBySlug), arg0, arg1)
}

// GetCategoryBySlugTx mocks base method.
func (m *MockBlogCategoryRepository) GetCategoryBySlugTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBySlugTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBySlugTx indicates an expected call of GetCategoryBySlugTx.
func (mr *MockBlogCategoryRepositoryMockRecorder) GetCategoryBySlugTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBySlugTx", reflect.TypeOf((*MockBlogCategoryRepository)(nil).GetCategoryBySlugTx), arg0, arg1, arg2)
}

// GetCategoryTx mocks base method.
func (m *MockBlogCategoryRepository) GetCategoryTx(arg0 context.Context, arg1 *sql.Tx, arg2 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryTx indicates an expected call of GetCategoryTx.
func (mr *MockBlogCategoryRepositoryMockRecorder) GetCategoryTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTx", reflect.TypeOf((*MockBlogCategoryRepository)(nil).GetCategoryTx), arg0, arg1, arg2)
}

// ListCategories mocks base method.
func (m *MockBlogCategoryRepository) ListCategories(arg0 context.Context) ([]*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", arg0)
	ret0, _ := ret[0].([]*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockBlogCategoryRepositoryMockRecorder) ListCategories(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockBlogCategoryRepository)(nil).ListCategories), arg0)
}

// UpdateCategory mocks base method.
func (m *MockBlogCategoryRepository) UpdateCategory(arg0 context.Context, arg1 *domain.BlogCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockBlogCategoryRepositoryMockRecorder) UpdateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockBlogCategoryRepository)(nil).UpdateCategory), arg0, arg1)
}

// UpdateCategoryTx mocks base method.
func (m *MockBlogCategoryRepository) UpdateCategoryTx(arg0 context.Context, arg1 *sql.Tx, arg2 *domain.BlogCategory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategoryTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategoryTx indicates an expected call of UpdateCategoryTx.
func (mr *MockBlogCategoryRepositoryMockRecorder) UpdateCategoryTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategoryTx", reflect.TypeOf((*MockBlogCategoryRepository)(nil).UpdateCategoryTx), arg0, arg1, arg2)
}

// WithTransaction mocks base method.
func (m *MockBlogCategoryRepository) WithTransaction(arg0 context.Context, arg1 string, arg2 func(*sql.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockBlogCategoryRepositoryMockRecorder) WithTransaction(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockBlogCategoryRepository)(nil).WithTransaction), arg0, arg1, arg2)
}
