// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: WebhookEventServiceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockWebhookEventServiceInterface is a mock of WebhookEventServiceInterface interface.
type MockWebhookEventServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookEventServiceInterfaceMockRecorder
}

// MockWebhookEventServiceInterfaceMockRecorder is the mock recorder for MockWebhookEventServiceInterface.
type MockWebhookEventServiceInterfaceMockRecorder struct {
	mock *MockWebhookEventServiceInterface
}

// NewMockWebhookEventServiceInterface creates a new mock instance.
func NewMockWebhookEventServiceInterface(ctrl *gomock.Controller) *MockWebhookEventServiceInterface {
	mock := &MockWebhookEventServiceInterface{ctrl: ctrl}
	mock.recorder = &MockWebhookEventServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookEventServiceInterface) EXPECT() *MockWebhookEventServiceInterfaceMockRecorder {
	return m.recorder
}

// ListEvents mocks base method.
func (m *MockWebhookEventServiceInterface) ListEvents(arg0 context.Context, arg1 string, arg2 domain.WebhookEventListParams) (*domain.WebhookEventListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.WebhookEventListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockWebhookEventServiceInterfaceMockRecorder) ListEvents(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockWebhookEventServiceInterface)(nil).ListEvents), arg0, arg1, arg2)
}

// ProcessWebhook mocks base method.
func (m *MockWebhookEventServiceInterface) ProcessWebhook(arg0 context.Context, arg1, arg2 string, arg3 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessWebhook", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessWebhook indicates an expected call of ProcessWebhook.
func (mr *MockWebhookEventServiceInterfaceMockRecorder) ProcessWebhook(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessWebhook", reflect.TypeOf((*MockWebhookEventServiceInterface)(nil).ProcessWebhook), arg0, arg1, arg2, arg3)
}
