// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: EmailProviderService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockEmailProviderService is a mock of EmailProviderService interface.
type MockEmailProviderService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailProviderServiceMockRecorder
}

// MockEmailProviderServiceMockRecorder is the mock recorder for MockEmailProviderService.
type MockEmailProviderServiceMockRecorder struct {
	mock *MockEmailProviderService
}

// NewMockEmailProviderService creates a new mock instance.
func NewMockEmailProviderService(ctrl *gomock.Controller) *MockEmailProviderService {
	mock := &MockEmailProviderService{ctrl: ctrl}
	mock.recorder = &MockEmailProviderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailProviderService) EXPECT() *MockEmailProviderServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockEmailProviderService) SendEmail(arg0 context.Context, arg1 domain.SendEmailProviderRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockEmailProviderServiceMockRecorder) SendEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockEmailProviderService)(nil).SendEmail), arg0, arg1)
}
