// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BlogService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBlogService is a mock of BlogService interface.
type MockBlogService struct {
	ctrl     *gomock.Controller
	recorder *MockBlogServiceMockRecorder
}

// MockBlogServiceMockRecorder is the mock recorder for MockBlogService.
type MockBlogServiceMockRecorder struct {
	mock *MockBlogService
}

// NewMockBlogService creates a new mock instance.
func NewMockBlogService(ctrl *gomock.Controller) *MockBlogService {
	mock := &MockBlogService{ctrl: ctrl}
	mock.recorder = &MockBlogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogService) EXPECT() *MockBlogServiceMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockBlogService) CreateCategory(arg0 context.Context, arg1 *domain.CreateBlogCategoryRequest) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockBlogServiceMockRecorder) CreateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockBlogService)(nil).CreateCategory), arg0, arg1)
}

// CreatePost mocks base method.
func (m *MockBlogService) CreatePost(arg0 context.Context, arg1 *domain.CreateBlogPostRequest) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockBlogServiceMockRecorder) CreatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockBlogService)(nil).CreatePost), arg0, arg1)
}

// CreateTheme mocks base method.
func (m *MockBlogService) CreateTheme(arg0 context.Context, arg1 *domain.CreateBlogThemeRequest) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTheme", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTheme indicates an expected call of CreateTheme.
func (mr *MockBlogServiceMockRecorder) CreateTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTheme", reflect.TypeOf((*MockBlogService)(nil).CreateTheme), arg0, arg1)
}

// DeleteCategory mocks base method.
func (m *MockBlogService) DeleteCategory(arg0 context.Context, arg1 *domain.DeleteBlogCategoryRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockBlogServiceMockRecorder) DeleteCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockBlogService)(nil).DeleteCategory), arg0, arg1)
}

// DeletePost mocks base method.
func (m *MockBlogService) DeletePost(arg0 context.Context, arg1 *domain.DeleteBlogPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePost indicates an expected call of DeletePost.
func (mr *MockBlogServiceMockRecorder) DeletePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePost", reflect.TypeOf((*MockBlogService)(nil).DeletePost), arg0, arg1)
}

// GetCategory mocks base method.
func (m *MockBlogService) GetCategory(arg0 context.Context, arg1 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategory", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategory indicates an expected call of GetCategory.
func (mr *MockBlogServiceMockRecorder) GetCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategory", reflect.TypeOf((*MockBlogService)(nil).GetCategory), arg0, arg1)
}

// GetCategoryBySlug mocks base method.
func (m *MockBlogService) GetCategoryBySlug(arg0 context.Context, arg1 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBySlug", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBySlug indicates an expected call of GetCategoryBySlug.
func (mr *MockBlogServiceMockRecorder) GetCategoryBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBySlug", reflect.TypeOf((*MockBlogService)(nil).GetCategoryBySlug), arg0, arg1)
}

// GetPost mocks base method.
func (m *MockBlogService) GetPost(arg0 context.Context, arg1 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockBlogServiceMockRecorder) GetPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockBlogService)(nil).GetPost), arg0, arg1)
}

// GetPostByCategoryAndSlug mocks base method.
func (m *MockBlogService) GetPostByCategoryAndSlug(arg0 context.Context, arg1, arg2 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByCategoryAndSlug", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByCategoryAndSlug indicates an expected call of GetPostByCategoryAndSlug.
func (mr *MockBlogServiceMockRecorder) GetPostByCategoryAndSlug(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByCategoryAndSlug", reflect.TypeOf((*MockBlogService)(nil).GetPostByCategoryAndSlug), arg0, arg1, arg2)
}

// GetPostBySlug mocks base method.
func (m *MockBlogService) GetPostBySlug(arg0 context.Context, arg1 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostBySlug", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostBySlug indicates an expected call of GetPostBySlug.
func (mr *MockBlogServiceMockRecorder) GetPostBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostBySlug", reflect.TypeOf((*MockBlogService)(nil).GetPostBySlug), arg0, arg1)
}

// GetPublicCategoryBySlug mocks base method.
func (m *MockBlogService) GetPublicCategoryBySlug(arg0 context.Context, arg1 string) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicCategoryBySlug", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicCategoryBySlug indicates an expected call of GetPublicCategoryBySlug.
func (mr *MockBlogServiceMockRecorder) GetPublicCategoryBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicCategoryBySlug", reflect.TypeOf((*MockBlogService)(nil).GetPublicCategoryBySlug), arg0, arg1)
}

// GetPublicPostByCategoryAndSlug mocks base method.
func (m *MockBlogService) GetPublicPostByCategoryAndSlug(arg0 context.Context, arg1, arg2 string) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicPostByCategoryAndSlug", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicPostByCategoryAndSlug indicates an expected call of GetPublicPostByCategoryAndSlug.
func (mr *MockBlogServiceMockRecorder) GetPublicPostByCategoryAndSlug(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicPostByCategoryAndSlug", reflect.TypeOf((*MockBlogService)(nil).GetPublicPostByCategoryAndSlug), arg0, arg1, arg2)
}

// GetPublishedTheme mocks base method.
func (m *MockBlogService) GetPublishedTheme(arg0 context.Context) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedTheme", arg0)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedTheme indicates an expected call of GetPublishedTheme.
func (mr *MockBlogServiceMockRecorder) GetPublishedTheme(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedTheme", reflect.TypeOf((*MockBlogService)(nil).GetPublishedTheme), arg0)
}

// GetTheme mocks base method.
func (m *MockBlogService) GetTheme(arg0 context.Context, arg1 int) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTheme", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTheme indicates an expected call of GetTheme.
func (mr *MockBlogServiceMockRecorder) GetTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTheme", reflect.TypeOf((*MockBlogService)(nil).GetTheme), arg0, arg1)
}

// ListCategories mocks base method.
func (m *MockBlogService) ListCategories(arg0 context.Context) (*domain.BlogCategoryListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", arg0)
	ret0, _ := ret[0].(*domain.BlogCategoryListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockBlogServiceMockRecorder) ListCategories(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockBlogService)(nil).ListCategories), arg0)
}

// ListPosts mocks base method.
func (m *MockBlogService) ListPosts(arg0 context.Context, arg1 *domain.ListBlogPostsRequest) (*domain.BlogPostListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPosts", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPostListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPosts indicates an expected call of ListPosts.
func (mr *MockBlogServiceMockRecorder) ListPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPosts", reflect.TypeOf((*MockBlogService)(nil).ListPosts), arg0, arg1)
}

// ListPublicPosts mocks base method.
func (m *MockBlogService) ListPublicPosts(arg0 context.Context, arg1 *domain.ListBlogPostsRequest) (*domain.BlogPostListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublicPosts", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPostListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublicPosts indicates an expected call of ListPublicPosts.
func (mr *MockBlogServiceMockRecorder) ListPublicPosts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublicPosts", reflect.TypeOf((*MockBlogService)(nil).ListPublicPosts), arg0, arg1)
}

// ListThemes mocks base method.
func (m *MockBlogService) ListThemes(arg0 context.Context, arg1 *domain.ListBlogThemesRequest) (*domain.BlogThemeListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListThemes", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogThemeListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListThemes indicates an expected call of ListThemes.
func (mr *MockBlogServiceMockRecorder) ListThemes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListThemes", reflect.TypeOf((*MockBlogService)(nil).ListThemes), arg0, arg1)
}

// PublishPost mocks base method.
func (m *MockBlogService) PublishPost(arg0 context.Context, arg1 *domain.PublishBlogPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPost indicates an expected call of PublishPost.
func (mr *MockBlogServiceMockRecorder) PublishPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPost", reflect.TypeOf((*MockBlogService)(nil).PublishPost), arg0, arg1)
}

// PublishTheme mocks base method.
func (m *MockBlogService) PublishTheme(arg0 context.Context, arg1 *domain.PublishBlogThemeRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTheme", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTheme indicates an expected call of PublishTheme.
func (mr *MockBlogServiceMockRecorder) PublishTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTheme", reflect.TypeOf((*MockBlogService)(nil).PublishTheme), arg0, arg1)
}

// RenderCategoryPage mocks base method.
func (m *MockBlogService) RenderCategoryPage(arg0 context.Context, arg1, arg2 string, arg3 int, arg4 *int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderCategoryPage", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderCategoryPage indicates an expected call of RenderCategoryPage.
func (mr *MockBlogServiceMockRecorder) RenderCategoryPage(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderCategoryPage", reflect.TypeOf((*MockBlogService)(nil).RenderCategoryPage), arg0, arg1, arg2, arg3, arg4)
}

// RenderHomePage mocks base method.
func (m *MockBlogService) RenderHomePage(arg0 context.Context, arg1 string, arg2 int, arg3 *int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderHomePage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderHomePage indicates an expected call of RenderHomePage.
func (mr *MockBlogServiceMockRecorder) RenderHomePage(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHomePage", reflect.TypeOf((*MockBlogService)(nil).RenderHomePage), arg0, arg1, arg2, arg3)
}

// RenderPostPage mocks base method.
func (m *MockBlogService) RenderPostPage(arg0 context.Context, arg1, arg2, arg3 string, arg4 *int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderPostPage", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderPostPage indicates an expected call of RenderPostPage.
func (mr *MockBlogServiceMockRecorder) RenderPostPage(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderPostPage", reflect.TypeOf((*MockBlogService)(nil).RenderPostPage), arg0, arg1, arg2, arg3, arg4)
}

// UnpublishPost mocks base method.
func (m *MockBlogService) UnpublishPost(arg0 context.Context, arg1 *domain.UnpublishBlogPostRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpublishPost", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpublishPost indicates an expected call of UnpublishPost.
func (mr *MockBlogServiceMockRecorder) UnpublishPost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpublishPost", reflect.TypeOf((*MockBlogService)(nil).UnpublishPost), arg0, arg1)
}

// UpdateCategory mocks base method.
func (m *MockBlogService) UpdateCategory(arg0 context.Context, arg1 *domain.UpdateBlogCategoryRequest) (*domain.BlogCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockBlogServiceMockRecorder) UpdateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockBlogService)(nil).UpdateCategory), arg0, arg1)
}

// UpdatePost mocks base method.
func (m *MockBlogService) UpdatePost(arg0 context.Context, arg1 *domain.UpdateBlogPostRequest) (*domain.BlogPost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePost", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogPost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePost indicates an expected call of UpdatePost.
func (mr *MockBlogServiceMockRecorder) UpdatePost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePost", reflect.TypeOf((*MockBlogService)(nil).UpdatePost), arg0, arg1)
}

// UpdateTheme mocks base method.
func (m *MockBlogService) UpdateTheme(arg0 context.Context, arg1 *domain.UpdateBlogThemeRequest) (*domain.BlogTheme, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTheme", arg0, arg1)
	ret0, _ := ret[0].(*domain.BlogTheme)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTheme indicates an expected call of UpdateTheme.
func (mr *MockBlogServiceMockRecorder) UpdateTheme(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTheme", reflect.TypeOf((*MockBlogService)(nil).UpdateTheme), arg0, arg1)
}
