// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: BroadcastSender)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockBroadcastSender is a mock of BroadcastSender interface.
type MockBroadcastSender struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastSenderMockRecorder
}

// MockBroadcastSenderMockRecorder is the mock recorder for MockBroadcastSender.
type MockBroadcastSenderMockRecorder struct {
	mock *MockBroadcastSender
}

// NewMockBroadcastSender creates a new mock instance.
func NewMockBroadcastSender(ctrl *gomock.Controller) *MockBroadcastSender {
	mock := &MockBroadcastSender{ctrl: ctrl}
	mock.recorder = &MockBroadcastSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastSender) EXPECT() *MockBroadcastSenderMockRecorder {
	return m.recorder
}

// GetBroadcast mocks base method.
func (m *MockBroadcastSender) GetBroadcast(arg0 context.Context, arg1, arg2 string) (*domain.Broadcast, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcast", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Broadcast)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBroadcast indicates an expected call of GetBroadcast.
func (mr *MockBroadcastSenderMockRecorder) GetBroadcast(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcast", reflect.TypeOf((*MockBroadcastSender)(nil).GetBroadcast), arg0, arg1, arg2)
}

// GetTemplateByID mocks base method.
func (m *MockBroadcastSender) GetTemplateByID(arg0 context.Context, arg1, arg2 string) (*domain.Template, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateByID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.Template)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateByID indicates an expected call of GetTemplateByID.
func (mr *MockBroadcastSenderMockRecorder) GetTemplateByID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateByID", reflect.TypeOf((*MockBroadcastSender)(nil).GetTemplateByID), arg0, arg1, arg2)
}

// RecordMessageSent mocks base method.
func (m *MockBroadcastSender) RecordMessageSent(arg0 context.Context, arg1 string, arg2 *domain.MessageHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordMessageSent", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordMessageSent indicates an expected call of RecordMessageSent.
func (mr *MockBroadcastSenderMockRecorder) RecordMessageSent(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMessageSent", reflect.TypeOf((*MockBroadcastSender)(nil).RecordMessageSent), arg0, arg1, arg2)
}

// UpdateMessageStatus mocks base method.
func (m *MockBroadcastSender) UpdateMessageStatus(arg0 context.Context, arg1, arg2 string, arg3 domain.MessageEvent, arg4 time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageStatus", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMessageStatus indicates an expected call of UpdateMessageStatus.
func (mr *MockBroadcastSenderMockRecorder) UpdateMessageStatus(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageStatus", reflect.TypeOf((*MockBroadcastSender)(nil).UpdateMessageStatus), arg0, arg1, arg2, arg3, arg4)
}
