// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: LLMService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockLLMService is a mock of LLMService interface.
type MockLLMService struct {
	ctrl     *gomock.Controller
	recorder *MockLLMServiceMockRecorder
}

// MockLLMServiceMockRecorder is the mock recorder for MockLLMService.
type MockLLMServiceMockRecorder struct {
	mock *MockLLMService
}

// NewMockLLMService creates a new mock instance.
func NewMockLLMService(ctrl *gomock.Controller) *MockLLMService {
	mock := &MockLLMService{ctrl: ctrl}
	mock.recorder = &MockLLMServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMService) EXPECT() *MockLLMServiceMockRecorder {
	return m.recorder
}

// StreamChat mocks base method.
func (m *MockLLMService) StreamChat(arg0 context.Context, arg1 *domain.LLMChatRequest, arg2 func(domain.LLMChatEvent) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamChat", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamChat indicates an expected call of StreamChat.
func (mr *MockLLMServiceMockRecorder) StreamChat(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamChat", reflect.TypeOf((*MockLLMService)(nil).StreamChat), arg0, arg1, arg2)
}
