// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/domain (interfaces: TemplateBlockService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockTemplateBlockService is a mock of TemplateBlockService interface.
type MockTemplateBlockService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateBlockServiceMockRecorder
}

// MockTemplateBlockServiceMockRecorder is the mock recorder for MockTemplateBlockService.
type MockTemplateBlockServiceMockRecorder struct {
	mock *MockTemplateBlockService
}

// NewMockTemplateBlockService creates a new mock instance.
func NewMockTemplateBlockService(ctrl *gomock.Controller) *MockTemplateBlockService {
	mock := &MockTemplateBlockService{ctrl: ctrl}
	mock.recorder = &MockTemplateBlockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateBlockService) EXPECT() *MockTemplateBlockServiceMockRecorder {
	return m.recorder
}

// CreateTemplateBlock mocks base method.
func (m *MockTemplateBlockService) CreateTemplateBlock(arg0 context.Context, arg1 string, arg2 *domain.TemplateBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTemplateBlock", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTemplateBlock indicates an expected call of CreateTemplateBlock.
func (mr *MockTemplateBlockServiceMockRecorder) CreateTemplateBlock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTemplateBlock", reflect.TypeOf((*MockTemplateBlockService)(nil).CreateTemplateBlock), arg0, arg1, arg2)
}

// DeleteTemplateBlock mocks base method.
func (m *MockTemplateBlockService) DeleteTemplateBlock(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTemplateBlock", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTemplateBlock indicates an expected call of DeleteTemplateBlock.
func (mr *MockTemplateBlockServiceMockRecorder) DeleteTemplateBlock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTemplateBlock", reflect.TypeOf((*MockTemplateBlockService)(nil).DeleteTemplateBlock), arg0, arg1, arg2)
}

// GetTemplateBlock mocks base method.
func (m *MockTemplateBlockService) GetTemplateBlock(arg0 context.Context, arg1, arg2 string) (*domain.TemplateBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTemplateBlock", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.TemplateBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTemplateBlock indicates an expected call of GetTemplateBlock.
func (mr *MockTemplateBlockServiceMockRecorder) GetTemplateBlock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTemplateBlock", reflect.TypeOf((*MockTemplateBlockService)(nil).GetTemplateBlock), arg0, arg1, arg2)
}

// ListTemplateBlocks mocks base method.
func (m *MockTemplateBlockService) ListTemplateBlocks(arg0 context.Context, arg1 string) ([]*domain.TemplateBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTemplateBlocks", arg0, arg1)
	ret0, _ := ret[0].([]*domain.TemplateBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTemplateBlocks indicates an expected call of ListTemplateBlocks.
func (mr *MockTemplateBlockServiceMockRecorder) ListTemplateBlocks(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTemplateBlocks", reflect.TypeOf((*MockTemplateBlockService)(nil).ListTemplateBlocks), arg0, arg1)
}

// UpdateTemplateBlock mocks base method.
func (m *MockTemplateBlockService) UpdateTemplateBlock(arg0 context.Context, arg1 string, arg2 *domain.TemplateBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTemplateBlock", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTemplateBlock indicates an expected call of UpdateTemplateBlock.
func (mr *MockTemplateBlockServiceMockRecorder) UpdateTemplateBlock(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTemplateBlock", reflect.TypeOf((*MockTemplateBlockService)(nil).UpdateTemplateBlock), arg0, arg1, arg2)
}
