import { HomeNav } from '../components/HomeNav'

export function PrivacyPolicyPage() {
    return (
        <div className="home-page">
            <HomeNav />

            <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 24px 80px' }}>
                <h1 style={{ fontSize: 32, fontWeight: 600, marginBottom: 8 }}>Privacy Policy</h1>
                <p style={{ color: '#888', marginBottom: 32 }}>Effective from 25 October 2024</p>

                <h2>Introduction</h2>
                <p>
                    Management Digital Marketing US ("Company", "We", "Us") is committed to providing quality services to its users ("You") and this policy outlines our ongoing obligations to You regarding how we manage Your Personal Information.
                </p>
                <p>
                    We comply with applicable data protection laws, including the California Consumer Privacy Act (CCPA) and the General Data Protection Regulation (GDPR) where applicable.
                </p>

                <h2>What is Personal Information and Why Do We Collect It?</h2>
                <p>Personal Information is information or an opinion that identifies an individual.</p>
                <p>Examples of Personal Information we collect include:</p>
                <ul>
                    <li>Names</li>
                    <li>Addresses</li>
                    <li>Email addresses</li>
                    <li>Phone numbers</li>
                </ul>
                <p>This Personal Information is obtained in various ways, including:</p>
                <ul>
                    <li>Via our website at https://smartmailai.com/ (the "Site")</li>
                    <li>When You communicate with Us via email, complete a survey, or provide feedback</li>
                    <li>From data provided by Your device with Your consent</li>
                    <li>From third-party services utilized by Us</li>
                </ul>
                <p>
                    We collect Your Personal Information for the primary purpose of providing our services, complying with legal obligations, and communicating with You, including marketing communications. You may unsubscribe from marketing communications at any time using the 'Unsubscribe' button in any marketing email. However, We reserve the right to send You notifications related to Our services and the operation of the Site.
                </p>
                <p>
                    We collect user email addresses and contact lists from Gmail via Google Workspace APIs, with user consent. This data is used solely to populate your personal address book within the application to enable seamless email composition and sending.
                </p>
                <p>Personal information We may collect includes:</p>
                <ul>
                    <li>Email address</li>
                    <li>Alternate sign-up or log-in methods where available</li>
                    <li>Device identifier generated by the Site</li>
                    <li>Your time spent on the Site</li>
                    <li>Content or services accessed through the Site</li>
                    <li>Web browser information</li>
                    <li>IP address</li>
                    <li>App performance data</li>
                </ul>

                <h2>How We Use Your Data</h2>
                <p>We use Your data to:</p>
                <ul>
                    <li>Provide Our services to You</li>
                    <li>Manage, maintain, and operate Our business and the Site</li>
                    <li>Suggest content or services based on Your use of the Site</li>
                    <li>To allow users to access and use their Gmail contacts directly within the platform</li>
                    <li>To facilitate sending emails from their own Gmail address, using selected contacts from their address book</li>
                </ul>
                <p>We do not sell Your data to third parties, except as specified in this Privacy Policy.</p>

                <h2>Sensitive Information</h2>
                <p>Sensitive information, including health information, will only be used by Us:</p>
                <ul>
                    <li>For the primary purpose for which it was obtained</li>
                    <li>With Your consent or where required or authorized by law</li>
                    <li>For a secondary purpose directly related to the primary purpose</li>
                </ul>
                <p>We may collect data related to Your use of the Site, including but not limited to analytics.</p>

                <h2>Third Parties</h2>
                <p>
                    Where reasonable and practicable, We collect Your Personal Information directly from You. However, We may receive information from third parties. In such cases, We take reasonable steps to ensure You are made aware of the information provided to Us.
                </p>

                <h3>Third-Party Services We Use</h3>
                <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 24 }}>
                    <thead>
                        <tr style={{ borderBottom: '2px solid #e5e5e5', textAlign: 'left' }}>
                            <th style={{ padding: '8px 12px' }}>Third Party Service</th>
                            <th style={{ padding: '8px 12px' }}>Purpose</th>
                            <th style={{ padding: '8px 12px' }}>Privacy Policy</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Azure</td>
                            <td style={{ padding: '8px 12px' }}>Storage of all user-generated emails</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://privacy.microsoft.com/en-us/PrivacyStatement" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Stripe</td>
                            <td style={{ padding: '8px 12px' }}>Used for purchasing credits</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://stripe.com/privacy" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>OpenAI</td>
                            <td style={{ padding: '8px 12px' }}>GPT models used to generate email content</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://openai.com/policies/privacy-policy" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Ideogram</td>
                            <td style={{ padding: '8px 12px' }}>Generates additional resources and images for emails</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://ideogram.ai/privacy" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Google Workspace APIs</td>
                            <td style={{ padding: '8px 12px' }}>Used for user authentication, accessing Gmail addresses, email contacts, and sending emails on the user's behalf</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Microsoft Clarity</td>
                            <td style={{ padding: '8px 12px' }}>Tracks user behavior for UX improvements</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://privacy.microsoft.com/en-us/privacystatement" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                        <tr style={{ borderBottom: '1px solid #e5e5e5' }}>
                            <td style={{ padding: '8px 12px' }}>Google Analytics</td>
                            <td style={{ padding: '8px 12px' }}>Site performance and user behavior</td>
                            <td style={{ padding: '8px 12px' }}><a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">Link</a></td>
                        </tr>
                    </tbody>
                </table>

                <h2>Disclosure of Personal Information</h2>
                <p>Your Personal Information may be disclosed:</p>
                <ul>
                    <li>To third parties where You consent to the use or disclosure</li>
                    <li>Where required or authorized by law</li>
                </ul>

                <h2>Security of Personal Information</h2>
                <p>
                    We store Your Personal Information securely to protect it from misuse, loss, and unauthorized access, modification, or disclosure. When Your Personal Information is no longer needed, We take reasonable steps to destroy or permanently de-identify it. However, most Personal Information is stored for a minimum of 7 years. All Personal Data is secured at rest using industry-standard encryption, and data is transmitted over a secure connection.
                </p>

                <h2>Access to your Personal Information</h2>
                <p>
                    You may access the Personal Information We hold about You and update and/or correct it, subject to certain exceptions. To access Your Personal Information, please contact Us in writing. We will not charge any fee for access requests, but We may charge an administrative fee for providing copies.
                </p>
                <p>
                    For security, We may require identification and other evidence before releasing requested information.
                </p>

                <h2>Maintaining the Quality of Your Personal Information</h2>
                <p>
                    We strive to ensure Your Personal Information is accurate, complete, and up to date. If You find any inaccuracies, please notify Us as soon as possible so We can update Our records.
                </p>

                <h2>Data Storage Outside the EU</h2>
                <p>
                    Your data may be stored in locations outside of the EU, including in countries where privacy protections differ. By using Our Site, You consent to storing Your Personal Information in these locations.
                </p>

                <h2>Your Data Protection Rights</h2>
                <p>You have the following data protection rights:</p>
                <ul>
                    <li><strong>Right to Access</strong> – You may request copies of Your Personal Data.</li>
                    <li><strong>Right to Rectification</strong> – You may request that We correct any inaccurate information.</li>
                    <li><strong>Right to Erasure</strong> – You may request that We erase Your Personal Data under certain conditions.</li>
                    <li><strong>Right to Restrict Processing</strong> – You may request that We restrict processing of Your Personal Data under certain conditions.</li>
                    <li><strong>Right to Object</strong> – You may object to Our processing of Your Personal Data under certain conditions.</li>
                    <li><strong>Right to Data Portability</strong> – You may request that We transfer Your data to another organization or to You under certain conditions.</li>
                </ul>
                <p>If You make a request, We have one month to respond. If You would like to exercise any of these rights, please contact Us using the details below.</p>

                <h2>Policy Updates</h2>
                <p>This Privacy Policy may change from time to time and is available on Our website.</p>

                <h2>Data Control</h2>
                <p>
                    All data collected is controlled by Management Digital Marketing US. Any data obtained is not used for developing, improving, or training generalized AI/ML models.
                </p>

                <h2>Privacy Policy Complaints and Enquiries</h2>
                <p>If You have any queries or complaints about Our Privacy Policy, please contact Us at:</p>
                <p>
                    <strong>The Data Controller</strong><br />
                    Management Digital Marketing US<br />
                    Conroe TX<br />
                    United States<br />
                    Email: ceo@mdm.ooo
                </p>
            </div>
        </div>
    )
}
