// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Notifuse/notifuse/internal/service/broadcast (interfaces: DataFeedFetcher)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/Notifuse/notifuse/internal/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockDataFeedFetcher is a mock of DataFeedFetcher interface.
type MockDataFeedFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockDataFeedFetcherMockRecorder
}

// MockDataFeedFetcherMockRecorder is the mock recorder for MockDataFeedFetcher.
type MockDataFeedFetcherMockRecorder struct {
	mock *MockDataFeedFetcher
}

// NewMockDataFeedFetcher creates a new mock instance.
func NewMockDataFeedFetcher(ctrl *gomock.Controller) *MockDataFeedFetcher {
	mock := &MockDataFeedFetcher{ctrl: ctrl}
	mock.recorder = &MockDataFeedFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataFeedFetcher) EXPECT() *MockDataFeedFetcherMockRecorder {
	return m.recorder
}

// FetchGlobal mocks base method.
func (m *MockDataFeedFetcher) FetchGlobal(arg0 context.Context, arg1 *domain.GlobalFeedSettings, arg2 *domain.GlobalFeedRequestPayload) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchGlobal", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchGlobal indicates an expected call of FetchGlobal.
func (mr *MockDataFeedFetcherMockRecorder) FetchGlobal(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchGlobal", reflect.TypeOf((*MockDataFeedFetcher)(nil).FetchGlobal), arg0, arg1, arg2)
}

// FetchRecipient mocks base method.
func (m *MockDataFeedFetcher) FetchRecipient(arg0 context.Context, arg1 *domain.RecipientFeedSettings, arg2 *domain.RecipientFeedRequestPayload) (map[string]interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRecipient", arg0, arg1, arg2)
	ret0, _ := ret[0].(map[string]interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRecipient indicates an expected call of FetchRecipient.
func (mr *MockDataFeedFetcherMockRecorder) FetchRecipient(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRecipient", reflect.TypeOf((*MockDataFeedFetcher)(nil).FetchRecipient), arg0, arg1, arg2)
}
